IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SELF_MT_APPROVEGETDOC]'))
DROP PROCEDURE [dbo].[SELF_MT_APPROVEGETDOC]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SELF_MT_APPROVEGETDOC]
(
	@CompID varchar (30),
	@JobType varchar (30),
	@Username varchar (20),
	@Status varchar (1),
	@fromDate varchar (20),
	@toDate varchar (20),
	@doc_count INT OUTPUT
)
AS
BEGIN
	IF @JobType = 'LEA' AND @Status = '0'
    BEGIN
       SELECT  SELF_TR_TIMELEAVE.COMPANY_CODE
		, SELF_TR_TIMELEAVE.WORKER_CODE
		, LEAVE_NAME_TH AS LEAVE_DETAIL_TH
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, LEAVE_NAME_EN AS LEAVE_DETAIL_EN
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMELEAVE_ID
		, ISNULL(TIMELEAVE_DOC, '') AS TIMELEAVE_DOC
		, TIMELEAVE_FROMDATE, TIMELEAVE_TODATE, TIMELEAVE_TYPE
		, ISNULL(TIMELEAVE_MIN, 0) AS TIMELEAVE_MIN, ISNULL(TIMELEAVE_ACTUALDAY, 0) AS TIMELEAVE_ACTUALDAY
		, ISNULL(TIMELEAVE_INCHOLIDAY, '0') AS TIMELEAVE_INCHOLIDAY
		, ISNULL(TIMELEAVE_DEDUCT, '0') AS TIMELEAVE_DEDUCT, ISNULL(TIMELEAVE_NOTE, '') AS TIMELEAVE_NOTE
		, SELF_TR_TIMELEAVE.LEAVE_CODE, ISNULL(SYS_MT_REASON.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(STATUS, 0) AS STATUS
		, ISNULL(SELF_TR_TIMELEAVE.MODIFIED_BY
		, SELF_TR_TIMELEAVE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMELEAVE.MODIFIED_DATE, SELF_TR_TIMELEAVE.CREATED_DATE) AS MODIFIED_DATE
		, SELF_MT_JOBTABLE.STATUS_JOB 
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMELEAVE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMELEAVE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMELEAVE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		INNER JOIN ATT_MT_LEAVE ON ATT_MT_LEAVE.COMPANY_CODE=SELF_TR_TIMELEAVE.COMPANY_CODE 
		AND ATT_MT_LEAVE.LEAVE_CODE=SELF_TR_TIMELEAVE.LEAVE_CODE 
		INNER JOIN SYS_MT_REASON ON ATT_MT_LEAVE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMELEAVE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'LEAVE' 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMELEAVE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMELEAVE.TIMELEAVE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate
		AND SELF_TR_TIMELEAVE.COMPANY_CODE=@CompID 
		AND SELF_TR_TIMELEAVE.TIMELEAVE_ID IN (SELECT
			SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		AND SELF_MT_JOBTABLE.JOBTABLE_ID NOT IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)
		)
		ORDER BY SELF_TR_TIMELEAVE.COMPANY_CODE, SELF_TR_TIMELEAVE.WORKER_CODE, TIMELEAVE_FROMDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
		IF @JobType = 'LEA' AND @Status = '1'
    BEGIN
       SELECT  SELF_TR_TIMELEAVE.COMPANY_CODE
		, SELF_TR_TIMELEAVE.WORKER_CODE
		, LEAVE_NAME_TH AS LEAVE_DETAIL_TH
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, LEAVE_NAME_EN AS LEAVE_DETAIL_EN
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMELEAVE_ID
		, ISNULL(TIMELEAVE_DOC, '') AS TIMELEAVE_DOC
		, TIMELEAVE_FROMDATE, TIMELEAVE_TODATE, TIMELEAVE_TYPE
		, ISNULL(TIMELEAVE_MIN, 0) AS TIMELEAVE_MIN, ISNULL(TIMELEAVE_ACTUALDAY, 0) AS TIMELEAVE_ACTUALDAY
		, ISNULL(TIMELEAVE_INCHOLIDAY, '0') AS TIMELEAVE_INCHOLIDAY
		, ISNULL(TIMELEAVE_DEDUCT, '0') AS TIMELEAVE_DEDUCT, ISNULL(TIMELEAVE_NOTE, '') AS TIMELEAVE_NOTE
		, SELF_TR_TIMELEAVE.LEAVE_CODE, ISNULL(SYS_MT_REASON.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(STATUS, 0) AS STATUS
		, ISNULL(SELF_TR_TIMELEAVE.MODIFIED_BY
		, SELF_TR_TIMELEAVE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMELEAVE.MODIFIED_DATE, SELF_TR_TIMELEAVE.CREATED_DATE) AS MODIFIED_DATE
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB 
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMELEAVE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMELEAVE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMELEAVE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		INNER JOIN ATT_MT_LEAVE ON ATT_MT_LEAVE.COMPANY_CODE=SELF_TR_TIMELEAVE.COMPANY_CODE 
		AND ATT_MT_LEAVE.LEAVE_CODE=SELF_TR_TIMELEAVE.LEAVE_CODE 
		INNER JOIN SYS_MT_REASON ON ATT_MT_LEAVE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMELEAVE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'LEAVE' 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMELEAVE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMELEAVE.TIMELEAVE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMELEAVE.COMPANY_CODE=@CompID 
		AND SELF_TR_TIMELEAVE.TIMELEAVE_ID IN (SELECT
			SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		OR SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)
		)
		ORDER BY SELF_TR_TIMELEAVE.COMPANY_CODE, SELF_TR_TIMELEAVE.WORKER_CODE, TIMELEAVE_FROMDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
		IF @JobType = 'LEA' AND @Status = '3'
    BEGIN
       SELECT  SELF_TR_TIMELEAVE.COMPANY_CODE
		, SELF_TR_TIMELEAVE.WORKER_CODE
		, LEAVE_NAME_TH AS LEAVE_DETAIL_TH
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, LEAVE_NAME_EN AS LEAVE_DETAIL_EN
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMELEAVE_ID
		, ISNULL(TIMELEAVE_DOC, '') AS TIMELEAVE_DOC
		, TIMELEAVE_FROMDATE, TIMELEAVE_TODATE, TIMELEAVE_TYPE
		, ISNULL(TIMELEAVE_MIN, 0) AS TIMELEAVE_MIN, ISNULL(TIMELEAVE_ACTUALDAY, 0) AS TIMELEAVE_ACTUALDAY
		, ISNULL(TIMELEAVE_INCHOLIDAY, '0') AS TIMELEAVE_INCHOLIDAY
		, ISNULL(TIMELEAVE_DEDUCT, '0') AS TIMELEAVE_DEDUCT, ISNULL(TIMELEAVE_NOTE, '') AS TIMELEAVE_NOTE
		, SELF_TR_TIMELEAVE.LEAVE_CODE, ISNULL(SYS_MT_REASON.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(STATUS, 0) AS STATUS
		, ISNULL(SELF_TR_TIMELEAVE.MODIFIED_BY
		, SELF_TR_TIMELEAVE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMELEAVE.MODIFIED_DATE, SELF_TR_TIMELEAVE.CREATED_DATE) AS MODIFIED_DATE
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB 
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMELEAVE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMELEAVE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMELEAVE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		INNER JOIN ATT_MT_LEAVE ON ATT_MT_LEAVE.COMPANY_CODE=SELF_TR_TIMELEAVE.COMPANY_CODE 
		AND ATT_MT_LEAVE.LEAVE_CODE=SELF_TR_TIMELEAVE.LEAVE_CODE 
		INNER JOIN SYS_MT_REASON ON ATT_MT_LEAVE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMELEAVE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'LEAVE' 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMELEAVE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMELEAVE.TIMELEAVE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMELEAVE.COMPANY_CODE=@CompID 
		AND SELF_TR_TIMELEAVE.TIMELEAVE_ID IN (SELECT
			SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)
		)
		AND SELF_MT_JOBTABLE.STATUS_JOB NOT IN ('C')
		ORDER BY SELF_TR_TIMELEAVE.COMPANY_CODE, SELF_TR_TIMELEAVE.WORKER_CODE, TIMELEAVE_FROMDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
		IF @JobType = 'LEA' AND @Status = '4'
    BEGIN
       SELECT  SELF_TR_TIMELEAVE.COMPANY_CODE
		, SELF_TR_TIMELEAVE.WORKER_CODE
		, LEAVE_NAME_TH AS LEAVE_DETAIL_TH
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, LEAVE_NAME_EN AS LEAVE_DETAIL_EN
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMELEAVE_ID
		, ISNULL(TIMELEAVE_DOC, '') AS TIMELEAVE_DOC
		, TIMELEAVE_FROMDATE, TIMELEAVE_TODATE, TIMELEAVE_TYPE
		, ISNULL(TIMELEAVE_MIN, 0) AS TIMELEAVE_MIN, ISNULL(TIMELEAVE_ACTUALDAY, 0) AS TIMELEAVE_ACTUALDAY
		, ISNULL(TIMELEAVE_INCHOLIDAY, '0') AS TIMELEAVE_INCHOLIDAY
		, ISNULL(TIMELEAVE_DEDUCT, '0') AS TIMELEAVE_DEDUCT, ISNULL(TIMELEAVE_NOTE, '') AS TIMELEAVE_NOTE
		, SELF_TR_TIMELEAVE.LEAVE_CODE, ISNULL(SYS_MT_REASON.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(STATUS, 0) AS STATUS
		, ISNULL(SELF_TR_TIMELEAVE.MODIFIED_BY
		, SELF_TR_TIMELEAVE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMELEAVE.MODIFIED_DATE, SELF_TR_TIMELEAVE.CREATED_DATE) AS MODIFIED_DATE
		, SELF_MT_JOBTABLE.STATUS_JOB 
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMELEAVE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMELEAVE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMELEAVE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		INNER JOIN ATT_MT_LEAVE ON ATT_MT_LEAVE.COMPANY_CODE=SELF_TR_TIMELEAVE.COMPANY_CODE 
		AND ATT_MT_LEAVE.LEAVE_CODE=SELF_TR_TIMELEAVE.LEAVE_CODE 
		INNER JOIN SYS_MT_REASON ON ATT_MT_LEAVE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMELEAVE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'LEAVE' 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMELEAVE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMELEAVE.TIMELEAVE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMELEAVE.COMPANY_CODE=@CompID 
		AND SELF_TR_TIMELEAVE.TIMELEAVE_ID IN (SELECT
			SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)
		)
		AND SELF_MT_JOBTABLE.STATUS_JOB IN ('C')
		ORDER BY SELF_TR_TIMELEAVE.COMPANY_CODE, SELF_TR_TIMELEAVE.WORKER_CODE, TIMELEAVE_FROMDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'SHT' AND @Status = '0'
    BEGIN
		SELECT  SELF_TR_TIMESHIFT.COMPANY_CODE
		, SELF_TR_TIMESHIFT.WORKER_CODE
		, TIMESHIFT_ID
		, ISNULL(TIMESHIFT_DOC, '') AS TIMESHIFT_DOC
		, TIMESHIFT_WORKDATE, TIMESHIFT_OLD
		, TIMESHIFT_NEW, ISNULL(TIMESHIFT_NOTE, '') AS TIMESHIFT_NOTE
		, ISNULL(SELF_TR_TIMESHIFT.REASON_CODE, '') AS REASON_CODE
		, ISNULL(REASON_NAME_TH, '') AS REASON_DETAIL_TH
		, ISNULL(ATT_MT_SHIFT.SHIFT_NAME_TH, '') AS SHIFT_NEW_TH
		, ISNULL(OLDSHIFT.SHIFT_NAME_TH, '') AS SHIFT_OLD_TH
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, ISNULL(REASON_NAME_EN, '') AS REASON_DETAIL_EN
		, ISNULL(ATT_MT_SHIFT.SHIFT_NAME_EN, '') AS SHIFT_NEW_EN
		, ISNULL(OLDSHIFT.SHIFT_NAME_EN, '') AS SHIFT_OLD_EN
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(STATUS, 0) AS STATUS
		, ISNULL(SELF_TR_TIMESHIFT.MODIFIED_BY
		, SELF_TR_TIMESHIFT.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMESHIFT.MODIFIED_DATE, SELF_TR_TIMESHIFT.CREATED_DATE) AS MODIFIED_DATE
		, SELF_MT_JOBTABLE.STATUS_JOB 
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMESHIFT 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMESHIFT.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		LEFT JOIN SYS_MT_REASON ON SYS_MT_REASON.REASON_CODE=SELF_TR_TIMESHIFT.REASON_CODE 
		AND REASON_GROUP = 'SHT' 
		INNER JOIN ATT_MT_SHIFT ON ATT_MT_SHIFT.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND ATT_MT_SHIFT.SHIFT_CODE=SELF_TR_TIMESHIFT.TIMESHIFT_NEW  
		INNER JOIN ATT_MT_SHIFT as OLDSHIFT ON OLDSHIFT.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND OLDSHIFT.SHIFT_CODE=SELF_TR_TIMESHIFT.TIMESHIFT_OLD  
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMESHIFT.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE   
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMESHIFT.TIMESHIFT_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMESHIFT.COMPANY_CODE=@CompID
		AND SELF_TR_TIMESHIFT.TIMESHIFT_ID IN (SELECT
			SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		AND SELF_MT_JOBTABLE.JOBTABLE_ID NOT IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType))
		ORDER BY SELF_TR_TIMESHIFT.COMPANY_CODE, SELF_TR_TIMESHIFT.WORKER_CODE, TIMESHIFT_WORKDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'SHT' AND @Status = '1'
    BEGIN
		SELECT  SELF_TR_TIMESHIFT.COMPANY_CODE
		, SELF_TR_TIMESHIFT.WORKER_CODE
		, TIMESHIFT_ID
		, ISNULL(TIMESHIFT_DOC, '') AS TIMESHIFT_DOC
		, TIMESHIFT_WORKDATE, TIMESHIFT_OLD
		, TIMESHIFT_NEW, ISNULL(TIMESHIFT_NOTE, '') AS TIMESHIFT_NOTE
		, ISNULL(SELF_TR_TIMESHIFT.REASON_CODE, '') AS REASON_CODE
		, ISNULL(REASON_NAME_TH, '') AS REASON_DETAIL_TH
		, ISNULL(ATT_MT_SHIFT.SHIFT_NAME_TH, '') AS SHIFT_NEW_TH
		, ISNULL(OLDSHIFT.SHIFT_NAME_TH, '') AS SHIFT_OLD_TH
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, ISNULL(REASON_NAME_EN, '') AS REASON_DETAIL_EN
		, ISNULL(ATT_MT_SHIFT.SHIFT_NAME_EN, '') AS SHIFT_NEW_EN
		, ISNULL(OLDSHIFT.SHIFT_NAME_EN, '') AS SHIFT_OLD_EN
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(STATUS, 0) AS STATUS
		, ISNULL(SELF_TR_TIMESHIFT.MODIFIED_BY
		, SELF_TR_TIMESHIFT.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMESHIFT.MODIFIED_DATE, SELF_TR_TIMESHIFT.CREATED_DATE) AS MODIFIED_DATE
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMESHIFT 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMESHIFT.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		LEFT JOIN SYS_MT_REASON ON SYS_MT_REASON.REASON_CODE=SELF_TR_TIMESHIFT.REASON_CODE 
		AND REASON_GROUP = 'SHT' 
		INNER JOIN ATT_MT_SHIFT ON ATT_MT_SHIFT.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND ATT_MT_SHIFT.SHIFT_CODE=SELF_TR_TIMESHIFT.TIMESHIFT_NEW  
		INNER JOIN ATT_MT_SHIFT as OLDSHIFT ON OLDSHIFT.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND OLDSHIFT.SHIFT_CODE=SELF_TR_TIMESHIFT.TIMESHIFT_OLD  
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMESHIFT.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE   
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMESHIFT.TIMESHIFT_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMESHIFT.COMPANY_CODE=@CompID
		AND SELF_TR_TIMESHIFT.TIMESHIFT_ID IN (SELECT
			SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		OR SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType))
		ORDER BY SELF_TR_TIMESHIFT.COMPANY_CODE, SELF_TR_TIMESHIFT.WORKER_CODE, TIMESHIFT_WORKDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'SHT' AND @Status = '3'
    BEGIN
		SELECT  SELF_TR_TIMESHIFT.COMPANY_CODE
		, SELF_TR_TIMESHIFT.WORKER_CODE
		, TIMESHIFT_ID
		, ISNULL(TIMESHIFT_DOC, '') AS TIMESHIFT_DOC
		, TIMESHIFT_WORKDATE, TIMESHIFT_OLD
		, TIMESHIFT_NEW, ISNULL(TIMESHIFT_NOTE, '') AS TIMESHIFT_NOTE
		, ISNULL(SELF_TR_TIMESHIFT.REASON_CODE, '') AS REASON_CODE
		, ISNULL(REASON_NAME_TH, '') AS REASON_DETAIL_TH
		, ISNULL(ATT_MT_SHIFT.SHIFT_NAME_TH, '') AS SHIFT_NEW_TH
		, ISNULL(OLDSHIFT.SHIFT_NAME_TH, '') AS SHIFT_OLD_TH
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, ISNULL(REASON_NAME_EN, '') AS REASON_DETAIL_EN
		, ISNULL(ATT_MT_SHIFT.SHIFT_NAME_EN, '') AS SHIFT_NEW_EN
		, ISNULL(OLDSHIFT.SHIFT_NAME_EN, '') AS SHIFT_OLD_EN
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(STATUS, 0) AS STATUS
		, ISNULL(SELF_TR_TIMESHIFT.MODIFIED_BY
		, SELF_TR_TIMESHIFT.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMESHIFT.MODIFIED_DATE, SELF_TR_TIMESHIFT.CREATED_DATE) AS MODIFIED_DATE
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMESHIFT 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMESHIFT.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		LEFT JOIN SYS_MT_REASON ON SYS_MT_REASON.REASON_CODE=SELF_TR_TIMESHIFT.REASON_CODE 
		AND REASON_GROUP = 'SHT' 
		INNER JOIN ATT_MT_SHIFT ON ATT_MT_SHIFT.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND ATT_MT_SHIFT.SHIFT_CODE=SELF_TR_TIMESHIFT.TIMESHIFT_NEW  
		INNER JOIN ATT_MT_SHIFT as OLDSHIFT ON OLDSHIFT.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND OLDSHIFT.SHIFT_CODE=SELF_TR_TIMESHIFT.TIMESHIFT_OLD  
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMESHIFT.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE   
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMESHIFT.TIMESHIFT_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMESHIFT.COMPANY_CODE=@CompID
		AND SELF_TR_TIMESHIFT.TIMESHIFT_ID IN (SELECT
			SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType))
		AND SELF_MT_JOBTABLE.STATUS_JOB NOT IN ('C')
		ORDER BY SELF_TR_TIMESHIFT.COMPANY_CODE, SELF_TR_TIMESHIFT.WORKER_CODE, TIMESHIFT_WORKDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'SHT' AND @Status = '4'
    BEGIN
		SELECT  SELF_TR_TIMESHIFT.COMPANY_CODE
		, SELF_TR_TIMESHIFT.WORKER_CODE
		, TIMESHIFT_ID
		, ISNULL(TIMESHIFT_DOC, '') AS TIMESHIFT_DOC
		, TIMESHIFT_WORKDATE, TIMESHIFT_OLD
		, TIMESHIFT_NEW, ISNULL(TIMESHIFT_NOTE, '') AS TIMESHIFT_NOTE
		, ISNULL(SELF_TR_TIMESHIFT.REASON_CODE, '') AS REASON_CODE
		, ISNULL(REASON_NAME_TH, '') AS REASON_DETAIL_TH
		, ISNULL(ATT_MT_SHIFT.SHIFT_NAME_TH, '') AS SHIFT_NEW_TH
		, ISNULL(OLDSHIFT.SHIFT_NAME_TH, '') AS SHIFT_OLD_TH
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, ISNULL(REASON_NAME_EN, '') AS REASON_DETAIL_EN
		, ISNULL(ATT_MT_SHIFT.SHIFT_NAME_EN, '') AS SHIFT_NEW_EN
		, ISNULL(OLDSHIFT.SHIFT_NAME_EN, '') AS SHIFT_OLD_EN
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(STATUS, 0) AS STATUS
		, ISNULL(SELF_TR_TIMESHIFT.MODIFIED_BY
		, SELF_TR_TIMESHIFT.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMESHIFT.MODIFIED_DATE, SELF_TR_TIMESHIFT.CREATED_DATE) AS MODIFIED_DATE
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMESHIFT 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMESHIFT.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		LEFT JOIN SYS_MT_REASON ON SYS_MT_REASON.REASON_CODE=SELF_TR_TIMESHIFT.REASON_CODE 
		AND REASON_GROUP = 'SHT' 
		INNER JOIN ATT_MT_SHIFT ON ATT_MT_SHIFT.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND ATT_MT_SHIFT.SHIFT_CODE=SELF_TR_TIMESHIFT.TIMESHIFT_NEW  
		INNER JOIN ATT_MT_SHIFT as OLDSHIFT ON OLDSHIFT.COMPANY_CODE=SELF_TR_TIMESHIFT.COMPANY_CODE 
		AND OLDSHIFT.SHIFT_CODE=SELF_TR_TIMESHIFT.TIMESHIFT_OLD  
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMESHIFT.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE   
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMESHIFT.TIMESHIFT_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMESHIFT.COMPANY_CODE=@CompID
		AND SELF_TR_TIMESHIFT.TIMESHIFT_ID IN (SELECT
			SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType))
		AND SELF_MT_JOBTABLE.STATUS_JOB IN ('C')
		ORDER BY SELF_TR_TIMESHIFT.COMPANY_CODE, SELF_TR_TIMESHIFT.WORKER_CODE, TIMESHIFT_WORKDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'OT' AND @Status = '0'
    BEGIN
		SELECT  SELF_TR_TIMEOT.COMPANY_CODE
		, SELF_TR_TIMEOT.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMEOT_ID, ISNULL(TIMEOT_DOC, '') AS TIMEOT_DOC, TIMEOT_WORKDATE
		, ISNULL(TIMEOT_BEFOREMIN, 0) AS TIMEOT_BEFOREMIN
		, ISNULL(TIMEOT_NORMALMIN, 0) AS TIMEOT_NORMALMIN
		, ISNULL(TIMEOT_BREAK, 0) AS TIMEOT_BREAK
		, ISNULL(TIMEOT_AFTERMIN, 0) AS TIMEOT_AFTERMIN
		, ISNULL(TIMEOT_NOTE, '') AS TIMEOT_NOTE
		, ISNULL(SELF_TR_TIMEOT.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(SELF_TR_TIMEOT.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(STATUS, 0) AS STATUS, ISNULL(SELF_TR_TIMEOT.MODIFIED_BY
		, SELF_TR_TIMEOT.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEOT.MODIFIED_DATE, SELF_TR_TIMEOT.CREATED_DATE) AS MODIFIED_DATE
		, SELF_MT_JOBTABLE.STATUS_JOB 
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMEOT 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEOT.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEOT.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEOT.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEOT.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'OT'  
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMEOT.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMEOT.LOCATION_CODE  
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEOT.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE  
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEOT.TIMEOT_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEOT.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEOT.TIMEOT_ID IN (
		SELECT
		SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		AND SELF_MT_JOBTABLE.JOBTABLE_ID NOT IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		ORDER BY SELF_TR_TIMEOT.COMPANY_CODE, SELF_TR_TIMEOT.WORKER_CODE, SELF_TR_TIMEOT.TIMEOT_WORKDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'OT' AND @Status = '1'
    BEGIN
		SELECT  SELF_TR_TIMEOT.COMPANY_CODE
		, SELF_TR_TIMEOT.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMEOT_ID, ISNULL(TIMEOT_DOC, '') AS TIMEOT_DOC, TIMEOT_WORKDATE
		, ISNULL(TIMEOT_BEFOREMIN, 0) AS TIMEOT_BEFOREMIN
		, ISNULL(TIMEOT_NORMALMIN, 0) AS TIMEOT_NORMALMIN
		, ISNULL(TIMEOT_BREAK, 0) AS TIMEOT_BREAK
		, ISNULL(TIMEOT_AFTERMIN, 0) AS TIMEOT_AFTERMIN
		, ISNULL(TIMEOT_NOTE, '') AS TIMEOT_NOTE
		, ISNULL(SELF_TR_TIMEOT.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(SELF_TR_TIMEOT.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(STATUS, 0) AS STATUS, ISNULL(SELF_TR_TIMEOT.MODIFIED_BY
		, SELF_TR_TIMEOT.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEOT.MODIFIED_DATE, SELF_TR_TIMEOT.CREATED_DATE) AS MODIFIED_DATE
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMEOT 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEOT.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEOT.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEOT.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEOT.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'OT'  
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMEOT.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMEOT.LOCATION_CODE  
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEOT.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE  
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEOT.TIMEOT_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEOT.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEOT.TIMEOT_ID IN (
		SELECT
		SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		OR SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		ORDER BY SELF_TR_TIMEOT.COMPANY_CODE, SELF_TR_TIMEOT.WORKER_CODE, SELF_TR_TIMEOT.TIMEOT_WORKDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'OT' AND @Status = '3'
    BEGIN
		SELECT  SELF_TR_TIMEOT.COMPANY_CODE
		, SELF_TR_TIMEOT.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMEOT_ID, ISNULL(TIMEOT_DOC, '') AS TIMEOT_DOC, TIMEOT_WORKDATE
		, ISNULL(TIMEOT_BEFOREMIN, 0) AS TIMEOT_BEFOREMIN
		, ISNULL(TIMEOT_NORMALMIN, 0) AS TIMEOT_NORMALMIN
		, ISNULL(TIMEOT_BREAK, 0) AS TIMEOT_BREAK
		, ISNULL(TIMEOT_AFTERMIN, 0) AS TIMEOT_AFTERMIN
		, ISNULL(TIMEOT_NOTE, '') AS TIMEOT_NOTE
		, ISNULL(SELF_TR_TIMEOT.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(SELF_TR_TIMEOT.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(STATUS, 0) AS STATUS, ISNULL(SELF_TR_TIMEOT.MODIFIED_BY
		, SELF_TR_TIMEOT.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEOT.MODIFIED_DATE, SELF_TR_TIMEOT.CREATED_DATE) AS MODIFIED_DATE
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMEOT 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEOT.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEOT.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEOT.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEOT.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'OT'  
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMEOT.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMEOT.LOCATION_CODE  
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEOT.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE  
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEOT.TIMEOT_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEOT.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEOT.TIMEOT_ID IN (
		SELECT
		SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType))
		AND SELF_MT_JOBTABLE.STATUS_JOB NOT IN ('C')
		ORDER BY SELF_TR_TIMEOT.COMPANY_CODE, SELF_TR_TIMEOT.WORKER_CODE, SELF_TR_TIMEOT.TIMEOT_WORKDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'OT' AND @Status = '4'
    BEGIN
		SELECT  SELF_TR_TIMEOT.COMPANY_CODE
		, SELF_TR_TIMEOT.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMEOT_ID, ISNULL(TIMEOT_DOC, '') AS TIMEOT_DOC, TIMEOT_WORKDATE
		, ISNULL(TIMEOT_BEFOREMIN, 0) AS TIMEOT_BEFOREMIN
		, ISNULL(TIMEOT_NORMALMIN, 0) AS TIMEOT_NORMALMIN
		, ISNULL(TIMEOT_BREAK, 0) AS TIMEOT_BREAK
		, ISNULL(TIMEOT_AFTERMIN, 0) AS TIMEOT_AFTERMIN
		, ISNULL(TIMEOT_NOTE, '') AS TIMEOT_NOTE
		, ISNULL(SELF_TR_TIMEOT.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(SELF_TR_TIMEOT.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(STATUS, 0) AS STATUS, ISNULL(SELF_TR_TIMEOT.MODIFIED_BY
		, SELF_TR_TIMEOT.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEOT.MODIFIED_DATE, SELF_TR_TIMEOT.CREATED_DATE) AS MODIFIED_DATE
		, SELF_MT_JOBTABLE.STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID 
		FROM SELF_TR_TIMEOT 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEOT.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEOT.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL  
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEOT.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEOT.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'OT'  
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMEOT.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMEOT.LOCATION_CODE  
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEOT.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE  
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEOT.TIMEOT_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEOT.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEOT.TIMEOT_ID IN (
		SELECT
		SELF_MT_JOBTABLE.JOB_ID
		FROM SELF_MT_JOBTABLE 
		JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
		AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
		WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
		AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
		SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
		JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
		AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
		WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
		AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType))
		AND SELF_MT_JOBTABLE.STATUS_JOB IN ('C')
		ORDER BY SELF_TR_TIMEOT.COMPANY_CODE, SELF_TR_TIMEOT.WORKER_CODE, SELF_TR_TIMEOT.TIMEOT_WORKDATE
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'DAT' AND @Status = '0'
    BEGIN
		SELECT SELF_TR_TIMEDAYTYPE.COMPANY_CODE
		, SELF_TR_TIMEDAYTYPE.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMEDAYTYPE_ID, TIMEDAYTYPE_DOC
		, TIMEDAYTYPE_WORKDATE
		, TIMEDAYTYPE_OLD, TIMEDAYTYPE_NEW
		, TIMEDAYTYPE_NOTE
		, ISNULL(SELF_TR_TIMEDAYTYPE.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, STATUS
		, ISNULL(SELF_TR_TIMEDAYTYPE.MODIFIED_BY
		, SELF_TR_TIMEDAYTYPE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEDAYTYPE.MODIFIED_DATE
		, SELF_TR_TIMEDAYTYPE.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMEDAYTYPE.FLAG, 0) AS FLAG 
		, SELF_MT_JOBTABLE.STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMEDAYTYPE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEDAYTYPE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEDAYTYPE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEDAYTYPE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEDAYTYPE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'DAT' 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEDAYTYPE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEDAYTYPE.TIMEDAYTYPE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEDAYTYPE.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEDAYTYPE.TIMEDAYTYPE_ID IN (
				SELECT
				SELF_MT_JOBTABLE.JOB_ID
				FROM SELF_MT_JOBTABLE 
				JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
				AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
				WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
				AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
				AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
				SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
				JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
				AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
				WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
				AND SELF_MT_JOBTABLE.JOBTABLE_ID NOT IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
				)
		ORDER BY TIMEDAYTYPE_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'DAT' AND @Status = '1'
    BEGIN
		SELECT SELF_TR_TIMEDAYTYPE.COMPANY_CODE
		, SELF_TR_TIMEDAYTYPE.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMEDAYTYPE_ID, TIMEDAYTYPE_DOC
		, TIMEDAYTYPE_WORKDATE
		, TIMEDAYTYPE_OLD, TIMEDAYTYPE_NEW
		, TIMEDAYTYPE_NOTE
		, ISNULL(SELF_TR_TIMEDAYTYPE.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, STATUS
		, ISNULL(SELF_TR_TIMEDAYTYPE.MODIFIED_BY
		, SELF_TR_TIMEDAYTYPE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEDAYTYPE.MODIFIED_DATE
		, SELF_TR_TIMEDAYTYPE.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMEDAYTYPE.FLAG, 0) AS FLAG 
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		,SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMEDAYTYPE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEDAYTYPE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEDAYTYPE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEDAYTYPE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEDAYTYPE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'DAT' 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEDAYTYPE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEDAYTYPE.TIMEDAYTYPE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEDAYTYPE.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEDAYTYPE.TIMEDAYTYPE_ID IN (
				SELECT
				SELF_MT_JOBTABLE.JOB_ID
				FROM SELF_MT_JOBTABLE 
				JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
				AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
				WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
				AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
				AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
				SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
				JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
				AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
				WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
				OR SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
				)
		ORDER BY TIMEDAYTYPE_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'DAT' AND @Status = '3'
    BEGIN
		SELECT SELF_TR_TIMEDAYTYPE.COMPANY_CODE
		, SELF_TR_TIMEDAYTYPE.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMEDAYTYPE_ID, TIMEDAYTYPE_DOC
		, TIMEDAYTYPE_WORKDATE
		, TIMEDAYTYPE_OLD, TIMEDAYTYPE_NEW
		, TIMEDAYTYPE_NOTE
		, ISNULL(SELF_TR_TIMEDAYTYPE.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, STATUS
		, ISNULL(SELF_TR_TIMEDAYTYPE.MODIFIED_BY
		, SELF_TR_TIMEDAYTYPE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEDAYTYPE.MODIFIED_DATE
		, SELF_TR_TIMEDAYTYPE.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMEDAYTYPE.FLAG, 0) AS FLAG 
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		,SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMEDAYTYPE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEDAYTYPE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEDAYTYPE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEDAYTYPE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEDAYTYPE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'DAT' 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEDAYTYPE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEDAYTYPE.TIMEDAYTYPE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEDAYTYPE.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEDAYTYPE.TIMEDAYTYPE_ID IN (
				SELECT
				SELF_MT_JOBTABLE.JOB_ID
				FROM SELF_MT_JOBTABLE 
				JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
				AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
				WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
				AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
				AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
				SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
				JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
				AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
				WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
				AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
				)
				AND SELF_MT_JOBTABLE.STATUS_JOB NOT IN ('C')
		ORDER BY TIMEDAYTYPE_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'DAT' AND @Status = '4'
    BEGIN
		SELECT SELF_TR_TIMEDAYTYPE.COMPANY_CODE
		, SELF_TR_TIMEDAYTYPE.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, TIMEDAYTYPE_ID, TIMEDAYTYPE_DOC
		, TIMEDAYTYPE_WORKDATE
		, TIMEDAYTYPE_OLD, TIMEDAYTYPE_NEW
		, TIMEDAYTYPE_NOTE
		, ISNULL(SELF_TR_TIMEDAYTYPE.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, STATUS
		, ISNULL(SELF_TR_TIMEDAYTYPE.MODIFIED_BY
		, SELF_TR_TIMEDAYTYPE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEDAYTYPE.MODIFIED_DATE
		, SELF_TR_TIMEDAYTYPE.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMEDAYTYPE.FLAG, 0) AS FLAG 
		, SELF_MT_JOBTABLE.STATUS_JOB
		,SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMEDAYTYPE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEDAYTYPE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEDAYTYPE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEDAYTYPE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEDAYTYPE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'DAT' 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEDAYTYPE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEDAYTYPE.TIMEDAYTYPE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEDAYTYPE.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEDAYTYPE.TIMEDAYTYPE_ID IN (
				SELECT
				SELF_MT_JOBTABLE.JOB_ID
				FROM SELF_MT_JOBTABLE 
				JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
				AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
				WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
				AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
				AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
				SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
				JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
				AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
				WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
				AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
				)
				AND SELF_MT_JOBTABLE.STATUS_JOB IN ('C')
		ORDER BY TIMEDAYTYPE_ID
		SELECT @doc_count = @@ROWCOUNT;
    END

	IF @JobType = 'ONS' AND @Status = '0'
    BEGIN
		SELECT  SELF_TR_TIMEONSITE.COMPANY_CODE
		, SELF_TR_TIMEONSITE.WORKER_CODE
		, SELF_TR_TIMEONSITE.TIMEONSITE_ID
		, SELF_TR_TIMEONSITE.TIMEONSITE_DOC
		, SELF_TR_TIMEONSITE.TIMEONSITE_WORKDATE
		, SELF_TR_TIMEONSITE.TIMEONSITE_IN
		, SELF_TR_TIMEONSITE.TIMEONSITE_OUT
		, SELF_TR_TIMEONSITE.TIMEONSITE_NOTE
		, SELF_TR_TIMEONSITE.STATUS
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(SELF_TR_TIMEONSITE.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(SELF_TR_TIMEONSITE.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(SELF_TR_TIMEONSITE.MODIFIED_BY
		, SELF_TR_TIMEONSITE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEONSITE.MODIFIED_DATE
		, SELF_TR_TIMEONSITE.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMEONSITE.FLAG, 0) AS FLAG
		, SELF_MT_JOBTABLE.STATUS_JOB 
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMEONSITE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEONSITE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEONSITE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEONSITE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEONSITE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'ONS' 
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMEONSITE.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMEONSITE.LOCATION_CODE 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEONSITE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEONSITE.TIMEONSITE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEONSITE.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEONSITE.TIMEONSITE_ID IN (
			SELECT
			SELF_MT_JOBTABLE.JOB_ID
			FROM SELF_MT_JOBTABLE 
			JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
			AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
			WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
			AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
			AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
			SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
			JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
			AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
			WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
			AND SELF_MT_JOBTABLE.JOBTABLE_ID NOT IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		ORDER BY SELF_TR_TIMEONSITE.TIMEONSITE_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'ONS' AND @Status = '1'
    BEGIN
		SELECT  SELF_TR_TIMEONSITE.COMPANY_CODE
		, SELF_TR_TIMEONSITE.WORKER_CODE
		, SELF_TR_TIMEONSITE.TIMEONSITE_ID
		, SELF_TR_TIMEONSITE.TIMEONSITE_DOC
		, SELF_TR_TIMEONSITE.TIMEONSITE_WORKDATE
		, SELF_TR_TIMEONSITE.TIMEONSITE_IN
		, SELF_TR_TIMEONSITE.TIMEONSITE_OUT
		, SELF_TR_TIMEONSITE.TIMEONSITE_NOTE
		, SELF_TR_TIMEONSITE.STATUS
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(SELF_TR_TIMEONSITE.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(SELF_TR_TIMEONSITE.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(SELF_TR_TIMEONSITE.MODIFIED_BY
		, SELF_TR_TIMEONSITE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEONSITE.MODIFIED_DATE
		, SELF_TR_TIMEONSITE.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMEONSITE.FLAG, 0) AS FLAG
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMEONSITE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEONSITE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEONSITE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEONSITE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEONSITE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'ONS' 
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMEONSITE.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMEONSITE.LOCATION_CODE 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEONSITE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEONSITE.TIMEONSITE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEONSITE.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEONSITE.TIMEONSITE_ID IN (
			SELECT
			SELF_MT_JOBTABLE.JOB_ID
			FROM SELF_MT_JOBTABLE 
			JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
			AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
			WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
			AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
			AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
			SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
			JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
			AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
			WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
			OR SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		ORDER BY SELF_TR_TIMEONSITE.TIMEONSITE_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'ONS' AND @Status = '3'
    BEGIN
		SELECT  SELF_TR_TIMEONSITE.COMPANY_CODE
		, SELF_TR_TIMEONSITE.WORKER_CODE
		, SELF_TR_TIMEONSITE.TIMEONSITE_ID
		, SELF_TR_TIMEONSITE.TIMEONSITE_DOC
		, SELF_TR_TIMEONSITE.TIMEONSITE_WORKDATE
		, SELF_TR_TIMEONSITE.TIMEONSITE_IN
		, SELF_TR_TIMEONSITE.TIMEONSITE_OUT
		, SELF_TR_TIMEONSITE.TIMEONSITE_NOTE
		, SELF_TR_TIMEONSITE.STATUS
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(SELF_TR_TIMEONSITE.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(SELF_TR_TIMEONSITE.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(SELF_TR_TIMEONSITE.MODIFIED_BY
		, SELF_TR_TIMEONSITE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEONSITE.MODIFIED_DATE
		, SELF_TR_TIMEONSITE.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMEONSITE.FLAG, 0) AS FLAG
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMEONSITE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEONSITE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEONSITE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEONSITE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEONSITE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'ONS' 
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMEONSITE.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMEONSITE.LOCATION_CODE 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEONSITE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEONSITE.TIMEONSITE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEONSITE.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEONSITE.TIMEONSITE_ID IN (
			SELECT
			SELF_MT_JOBTABLE.JOB_ID
			FROM SELF_MT_JOBTABLE 
			JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
			AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
			WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
			AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
			AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
			SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
			JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
			AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
			WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
			AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		AND SELF_MT_JOBTABLE.STATUS_JOB NOT IN ('C')
		ORDER BY SELF_TR_TIMEONSITE.TIMEONSITE_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'ONS' AND @Status = '4'
    BEGIN
		SELECT  SELF_TR_TIMEONSITE.COMPANY_CODE
		, SELF_TR_TIMEONSITE.WORKER_CODE
		, SELF_TR_TIMEONSITE.TIMEONSITE_ID
		, SELF_TR_TIMEONSITE.TIMEONSITE_DOC
		, SELF_TR_TIMEONSITE.TIMEONSITE_WORKDATE
		, SELF_TR_TIMEONSITE.TIMEONSITE_IN
		, SELF_TR_TIMEONSITE.TIMEONSITE_OUT
		, SELF_TR_TIMEONSITE.TIMEONSITE_NOTE
		, SELF_TR_TIMEONSITE.STATUS
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(SELF_TR_TIMEONSITE.REASON_CODE, '') AS REASON_CODE
		, ISNULL(SYS_MT_REASON.REASON_NAME_TH, '') AS REASON_NAME_TH
		, ISNULL(SYS_MT_REASON.REASON_NAME_EN, '') AS REASON_NAME_EN
		, ISNULL(SELF_TR_TIMEONSITE.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, ISNULL(SELF_TR_TIMEONSITE.MODIFIED_BY
		, SELF_TR_TIMEONSITE.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMEONSITE.MODIFIED_DATE
		, SELF_TR_TIMEONSITE.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMEONSITE.FLAG, 0) AS FLAG
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMEONSITE 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMEONSITE.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMEONSITE.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_REASON ON SELF_TR_TIMEONSITE.COMPANY_CODE=SYS_MT_REASON.COMPANY_CODE 
		AND SYS_MT_REASON.REASON_CODE=SELF_TR_TIMEONSITE.REASON_CODE 
		AND SYS_MT_REASON.REASON_GROUP = 'ONS' 
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMEONSITE.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMEONSITE.LOCATION_CODE 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMEONSITE.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMEONSITE.TIMEONSITE_ID 
		AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMEONSITE.COMPANY_CODE=@CompID
		AND SELF_TR_TIMEONSITE.TIMEONSITE_ID IN (
			SELECT
			SELF_MT_JOBTABLE.JOB_ID
			FROM SELF_MT_JOBTABLE 
			JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
			AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
			WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
			AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
			AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
			SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
			JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
			AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
			WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
			AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		AND SELF_MT_JOBTABLE.STATUS_JOB IN ('C')
		ORDER BY SELF_TR_TIMEONSITE.TIMEONSITE_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'CI' AND @Status = '0'
    BEGIN
		SELECT SELF_TR_TIMECHECKIN.COMPANY_CODE
		, TIMECHECKIN_ID, TIMECHECKIN_DOC
		, TIMECHECKIN_WORKDATE
		, TIMECHECKIN_TIME
		, TIMECHECKIN_TYPE
		, TIMECHECKIN_LAT
		, TIMECHECKIN_LONG
		, TIMECHECKIN_NOTE
		, ISNULL(SELF_TR_TIMECHECKIN.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, SELF_TR_TIMECHECKIN.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(SELF_TR_TIMECHECKIN.MODIFIED_BY
		, SELF_TR_TIMECHECKIN.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMECHECKIN.MODIFIED_DATE
		, SELF_TR_TIMECHECKIN.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMECHECKIN.FLAG, 0) AS FLAG
		, SELF_TR_TIMECHECKIN.STATUS
		, SELF_MT_JOBTABLE.STATUS_JOB 
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMECHECKIN 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMECHECKIN.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMECHECKIN.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMECHECKIN.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMECHECKIN.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE  
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMECHECKIN.TIMECHECKIN_ID AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMECHECKIN.LOCATION_CODE WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMECHECKIN.COMPANY_CODE=@CompID
		AND SELF_TR_TIMECHECKIN.TIMECHECKIN_ID IN (
		SELECT
					SELF_MT_JOBTABLE.JOB_ID
					FROM SELF_MT_JOBTABLE 
					JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
					AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
					WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
					AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
					AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
					SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
					JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
					AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
					WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
					AND SELF_MT_JOBTABLE.JOBTABLE_ID NOT IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		ORDER BY TIMECHECKIN_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'CI' AND @Status = '1'
    BEGIN
		SELECT SELF_TR_TIMECHECKIN.COMPANY_CODE
		, TIMECHECKIN_ID, TIMECHECKIN_DOC
		, TIMECHECKIN_WORKDATE
		, TIMECHECKIN_TIME
		, TIMECHECKIN_TYPE
		, TIMECHECKIN_LAT
		, TIMECHECKIN_LONG
		, TIMECHECKIN_NOTE
		, ISNULL(SELF_TR_TIMECHECKIN.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, SELF_TR_TIMECHECKIN.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(SELF_TR_TIMECHECKIN.MODIFIED_BY
		, SELF_TR_TIMECHECKIN.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMECHECKIN.MODIFIED_DATE
		, SELF_TR_TIMECHECKIN.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMECHECKIN.FLAG, 0) AS FLAG
		, SELF_TR_TIMECHECKIN.STATUS
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMECHECKIN 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMECHECKIN.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMECHECKIN.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMECHECKIN.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMECHECKIN.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE  
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMECHECKIN.TIMECHECKIN_ID AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMECHECKIN.LOCATION_CODE WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMECHECKIN.COMPANY_CODE=@CompID
		AND SELF_TR_TIMECHECKIN.TIMECHECKIN_ID IN (
		SELECT
					SELF_MT_JOBTABLE.JOB_ID
					FROM SELF_MT_JOBTABLE 
					JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
					AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
					WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
					AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
					AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
					SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
					JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
					AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
					WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
					OR SELF_MT_JOBTABLE.JOBTABLE_ID  IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		ORDER BY TIMECHECKIN_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'CI' AND @Status = '3'
    BEGIN
		SELECT SELF_TR_TIMECHECKIN.COMPANY_CODE
		, TIMECHECKIN_ID, TIMECHECKIN_DOC
		, TIMECHECKIN_WORKDATE
		, TIMECHECKIN_TIME
		, TIMECHECKIN_TYPE
		, TIMECHECKIN_LAT
		, TIMECHECKIN_LONG
		, TIMECHECKIN_NOTE
		, ISNULL(SELF_TR_TIMECHECKIN.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, SELF_TR_TIMECHECKIN.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(SELF_TR_TIMECHECKIN.MODIFIED_BY
		, SELF_TR_TIMECHECKIN.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMECHECKIN.MODIFIED_DATE
		, SELF_TR_TIMECHECKIN.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMECHECKIN.FLAG, 0) AS FLAG
		, SELF_TR_TIMECHECKIN.STATUS
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMECHECKIN 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMECHECKIN.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMECHECKIN.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMECHECKIN.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMECHECKIN.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE  
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMECHECKIN.TIMECHECKIN_ID AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMECHECKIN.LOCATION_CODE WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMECHECKIN.COMPANY_CODE=@CompID
		AND SELF_TR_TIMECHECKIN.TIMECHECKIN_ID IN (
		SELECT
					SELF_MT_JOBTABLE.JOB_ID
					FROM SELF_MT_JOBTABLE 
					JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
					AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
					WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
					AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
					AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
					SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
					JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
					AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
					WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
					AND SELF_MT_JOBTABLE.JOBTABLE_ID  IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		AND SELF_MT_JOBTABLE.STATUS_JOB NOT IN ('C')
		ORDER BY TIMECHECKIN_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'CI' AND @Status = '4'
    BEGIN
		SELECT SELF_TR_TIMECHECKIN.COMPANY_CODE
		, TIMECHECKIN_ID, TIMECHECKIN_DOC
		, TIMECHECKIN_WORKDATE
		, TIMECHECKIN_TIME
		, TIMECHECKIN_TYPE
		, TIMECHECKIN_LAT
		, TIMECHECKIN_LONG
		, TIMECHECKIN_NOTE
		, ISNULL(SELF_TR_TIMECHECKIN.LOCATION_CODE, '') AS LOCATION_CODE
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_TH, '') AS LOCATION_NAME_TH
		, ISNULL(SYS_MT_LOCATION.LOCATION_NAME_EN, '') AS LOCATION_NAME_EN
		, SELF_TR_TIMECHECKIN.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, ISNULL(SELF_TR_TIMECHECKIN.MODIFIED_BY
		, SELF_TR_TIMECHECKIN.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_TR_TIMECHECKIN.MODIFIED_DATE
		, SELF_TR_TIMECHECKIN.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_TR_TIMECHECKIN.FLAG, 0) AS FLAG
		, SELF_TR_TIMECHECKIN.STATUS
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_TR_TIMECHECKIN 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_TR_TIMECHECKIN.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_TR_TIMECHECKIN.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SYS_MT_LOCATION ON SELF_TR_TIMECHECKIN.COMPANY_CODE=SYS_MT_LOCATION.COMPANY_CODE 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_TR_TIMECHECKIN.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE  
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_TR_TIMECHECKIN.TIMECHECKIN_ID AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType  
		AND SYS_MT_LOCATION.LOCATION_CODE=SELF_TR_TIMECHECKIN.LOCATION_CODE WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_TR_TIMECHECKIN.COMPANY_CODE=@CompID
		AND SELF_TR_TIMECHECKIN.TIMECHECKIN_ID IN (
		SELECT
					SELF_MT_JOBTABLE.JOB_ID
					FROM SELF_MT_JOBTABLE 
					JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
					AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
					WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
					AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
					AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
					SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
					JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
					AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
					WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
					AND SELF_MT_JOBTABLE.JOBTABLE_ID  IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		AND SELF_MT_JOBTABLE.STATUS_JOB  IN ('C')
		ORDER BY TIMECHECKIN_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
	IF @JobType = 'REQ' AND @Status = '0'
    BEGIN
		SELECT SELF_MT_REQDOC.COMPANY_CODE
		, SELF_MT_REQDOC.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, SELF_MT_REQDOC.REQDOC_ID
		, SELF_MT_REQDOC.REQDOC_DOC
		, SELF_MT_REQDOC.REQDOC_DATE
		, SELF_MT_REQDOC.REQDOC_NOTE
		, SELF_MT_REQDOC.STATUS
		, ISNULL(SELF_MT_REQDOC.MODIFIED_BY, SELF_MT_REQDOC.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_MT_REQDOC.MODIFIED_DATE, SELF_MT_REQDOC.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_MT_REQDOC.FLAG, 0) AS FLAG
		, SELF_MT_JOBTABLE.STATUS_JOB 
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_MT_REQDOC 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_MT_REQDOC.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_MT_REQDOC.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_MT_REQDOC.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_MT_REQDOC.REQDOC_ID AND SELF_MT_JOBTABLE.JOB_TYPE = 'REQ' 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_MT_REQDOC.COMPANY_CODE=@CompID
		AND SELF_MT_REQDOC.REQDOC_ID IN (
			SELECT
			SELF_MT_JOBTABLE.JOB_ID
			FROM SELF_MT_JOBTABLE 
			JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
			AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
			WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
			AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
			AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
			SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
			JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
			AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
			WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
			AND SELF_MT_JOBTABLE.JOBTABLE_ID NOT IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		ORDER BY SELF_MT_REQDOC.REQDOC_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
		IF @JobType = 'REQ' AND @Status = '1'
    BEGIN
		SELECT SELF_MT_REQDOC.COMPANY_CODE
		, SELF_MT_REQDOC.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, SELF_MT_REQDOC.REQDOC_ID
		, SELF_MT_REQDOC.REQDOC_DOC
		, SELF_MT_REQDOC.REQDOC_DATE
		, SELF_MT_REQDOC.REQDOC_NOTE
		, SELF_MT_REQDOC.STATUS
		, ISNULL(SELF_MT_REQDOC.MODIFIED_BY, SELF_MT_REQDOC.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_MT_REQDOC.MODIFIED_DATE, SELF_MT_REQDOC.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_MT_REQDOC.FLAG, 0) AS FLAG
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_MT_REQDOC 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_MT_REQDOC.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_MT_REQDOC.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_MT_REQDOC.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_MT_REQDOC.REQDOC_ID AND SELF_MT_JOBTABLE.JOB_TYPE = 'REQ' 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_MT_REQDOC.COMPANY_CODE=@CompID
		AND SELF_MT_REQDOC.REQDOC_ID IN (
			SELECT
			SELF_MT_JOBTABLE.JOB_ID
			FROM SELF_MT_JOBTABLE 
			JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
			AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
			WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
			AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
			AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
			SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
			JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
			AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
			WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
			OR SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		ORDER BY SELF_MT_REQDOC.REQDOC_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
		IF @JobType = 'REQ' AND @Status = '3'
    BEGIN
		SELECT SELF_MT_REQDOC.COMPANY_CODE
		, SELF_MT_REQDOC.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, SELF_MT_REQDOC.REQDOC_ID
		, SELF_MT_REQDOC.REQDOC_DOC
		, SELF_MT_REQDOC.REQDOC_DATE
		, SELF_MT_REQDOC.REQDOC_NOTE
		, SELF_MT_REQDOC.STATUS
		, ISNULL(SELF_MT_REQDOC.MODIFIED_BY, SELF_MT_REQDOC.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_MT_REQDOC.MODIFIED_DATE, SELF_MT_REQDOC.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_MT_REQDOC.FLAG, 0) AS FLAG
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_MT_REQDOC 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_MT_REQDOC.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_MT_REQDOC.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_MT_REQDOC.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_MT_REQDOC.REQDOC_ID AND SELF_MT_JOBTABLE.JOB_TYPE = 'REQ' 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_MT_REQDOC.COMPANY_CODE=@CompID
		AND SELF_MT_REQDOC.REQDOC_ID IN (
			SELECT
			SELF_MT_JOBTABLE.JOB_ID
			FROM SELF_MT_JOBTABLE 
			JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
			AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
			WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
			AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
			AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
			SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
			JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
			AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
			WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
			AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		AND SELF_MT_JOBTABLE.STATUS_JOB NOT IN ('C')
		ORDER BY SELF_MT_REQDOC.REQDOC_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
		IF @JobType = 'REQ' AND @Status = '4'
    BEGIN
		SELECT SELF_MT_REQDOC.COMPANY_CODE
		, SELF_MT_REQDOC.WORKER_CODE
		, INITIAL_NAME_TH + WORKER_FNAME_TH + ' ' + WORKER_LNAME_TH AS WORKER_DETAIL_TH
		, INITIAL_NAME_EN + WORKER_FNAME_EN + ' ' + WORKER_LNAME_EN AS WORKER_DETAIL_EN
		, SELF_MT_REQDOC.REQDOC_ID
		, SELF_MT_REQDOC.REQDOC_DOC
		, SELF_MT_REQDOC.REQDOC_DATE
		, SELF_MT_REQDOC.REQDOC_NOTE
		, SELF_MT_REQDOC.STATUS
		, ISNULL(SELF_MT_REQDOC.MODIFIED_BY, SELF_MT_REQDOC.CREATED_BY) AS MODIFIED_BY
		, ISNULL(SELF_MT_REQDOC.MODIFIED_DATE, SELF_MT_REQDOC.CREATED_DATE) AS MODIFIED_DATE
		, ISNULL(SELF_MT_REQDOC.FLAG, 0) AS FLAG
		, CASE
			WHEN SELF_MT_JOBTABLE.STATUS_JOB = 'W' AND  SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER= @Username AND JOB_TYPE=@JobType)  THEN 'F'
			ELSE SELF_MT_JOBTABLE.STATUS_JOB
		  END AS STATUS_JOB  
		, SELF_MT_JOBTABLE.JOBTABLE_ID
		FROM SELF_MT_REQDOC 
		INNER JOIN EMP_MT_WORKER ON EMP_MT_WORKER.COMPANY_CODE=SELF_MT_REQDOC.COMPANY_CODE 
		AND EMP_MT_WORKER.WORKER_CODE=SELF_MT_REQDOC.WORKER_CODE 
		INNER JOIN EMP_MT_INITIAL ON EMP_MT_INITIAL.INITIAL_CODE=EMP_MT_WORKER.WORKER_INITIAL 
		INNER JOIN SELF_MT_JOBTABLE ON SELF_MT_REQDOC.COMPANY_CODE=SELF_MT_JOBTABLE.COMPANY_CODE 
		AND SELF_MT_JOBTABLE.JOB_ID = SELF_MT_REQDOC.REQDOC_ID AND SELF_MT_JOBTABLE.JOB_TYPE = 'REQ' 
		WHERE 1=1 AND SELF_MT_JOBTABLE.JOB_DATE BETWEEN @fromDate AND @toDate  
		AND SELF_MT_REQDOC.COMPANY_CODE=@CompID
		AND SELF_MT_REQDOC.REQDOC_ID IN (
			SELECT
			SELF_MT_JOBTABLE.JOB_ID
			FROM SELF_MT_JOBTABLE 
			JOIN SELF_TR_LINEAPPROVE ON SELF_TR_LINEAPPROVE.COMPANY_CODE = SELF_MT_JOBTABLE.COMPANY_CODE
			AND SELF_TR_LINEAPPROVE.WORKFLOW_CODE = SELF_MT_JOBTABLE.WORKFLOW_CODE
			WHERE SELF_MT_JOBTABLE.COMPANY_CODE = @CompID
			AND SELF_MT_JOBTABLE.JOB_TYPE = @JobType
			AND SELF_TR_LINEAPPROVE.POSITION_LEVEL IN (
			SELECT DISTINCT EMP_MT_POSITION.POSITION_LEVEL FROM SELF_TR_ACCOUNTPOS
			JOIN  EMP_MT_POSITION ON EMP_MT_POSITION.COMPANY_CODE = SELF_TR_ACCOUNTPOS.COMPANY_CODE
			AND EMP_MT_POSITION.POSITION_CODE = SELF_TR_ACCOUNTPOS.POSITION_CODE
			WHERE SELF_TR_ACCOUNTPOS.ACCOUNT_USER = @Username)
			AND SELF_MT_JOBTABLE.JOBTABLE_ID IN (SELECT JOBTABLE_ID FROM SELF_TR_APPROVE WHERE COMPANY_CODE=@CompID AND APPROVE_USER=@Username AND JOB_TYPE=@JobType)
		)
		AND SELF_MT_JOBTABLE.STATUS_JOB IN ('C')
		ORDER BY SELF_MT_REQDOC.REQDOC_ID
		SELECT @doc_count = @@ROWCOUNT;
    END
END
GO