USE [OPR]
GO

/****** Object:  Table [dbo].[EMP_TR_BENEFIT]    Script Date: 24/10/2023 08:34:09 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMP_TR_BENEFIT]') AND type in (N'U'))
DROP TABLE [dbo].[EMP_TR_BENEFIT]
GO

/****** Object:  Table [dbo].[EMP_TR_BENEFIT]    Script Date: 24/10/2023 08:34:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMP_TR_BENEFIT](
	[COMPANY_CODE] [varchar](20) NOT NULL,
	[WORKER_CODE] [varchar](15) NOT NULL,
	[EMPBENEFIT_ID] [int] NOT NULL,
	[ITEM_CODE] [varchar](20) NOT NULL,
	[EMPBENEFIT_AMOUNT] [decimal](10, 2) NOT NULL,
	[EMPBENEFIT_STARTDATE] [datetime] NOT NULL,
	[EMPBENEFIT_ENDDATE] [datetime] NOT NULL,
	[EMPBENEFIT_REASON] [varchar](3) NOT NULL,
	[EMPBENEFIT_NOTE] [varchar](100) NULL,
	[CREATED_BY] [varchar](20) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](20) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[FLAG] [bit] NOT NULL,
	[EMPBENEFIT_PAYTYPE] [char](1) NULL,
	[EMPBENEFIT_BREAK] [bit] NULL,
	[EMPBENEFIT_BREAKREASON] [varchar](3) NULL,
	[EMPBENEFIT_CONDITIONPAY] [char](1) NULL,
	[EMPBENEFIT_PAYFIRST] [char](1) NULL,
	[EMPBENEFIT_CAPITALAMOUNT] [decimal](10, 2) NULL,
	[EMPBENEFIT_PERIOD] [decimal](5, 2) NULL,
 CONSTRAINT [PK_EMP_TR_BENEFIT] PRIMARY KEY CLUSTERED 
(
	[COMPANY_CODE] ASC,
	[WORKER_CODE] ASC,
	[ITEM_CODE] ASC,
	[EMPBENEFIT_STARTDATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


