USE [OPR]
GO

/****** Object:  Table [dbo].[REQ_TR_POSITION]    Script Date: 01/11/2023 10:18:31 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[REQ_TR_POSITION]') AND type in (N'U'))
DROP TABLE [dbo].[REQ_TR_POSITION]
GO

/****** Object:  Table [dbo].[REQ_TR_POSITION]    Script Date: 01/11/2023 10:18:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[REQ_TR_POSITION](
	[COMPANY_CODE] [varchar](20) NOT NULL,
	[WORKER_CODE] [varchar](15) NOT NULL,
	[EMPPOSITION_ID] [int] NOT NULL,
	[EMPPOSITION_POSITION] [varchar](10) NOT NULL,
	[REQUEST_CODE] [varchar](5) NULL,
	[CREATED_BY] [varchar](20) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](20) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[FLAG] [bit] NOT NULL,
 CONSTRAINT [PK_REQ_TR_POSITION] PRIMARY KEY CLUSTERED 
(
	[COMPANY_CODE] ASC,
	[WORKER_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


